version: '3'

services:
  mysql:
    image:  'mysql/mysql-server:8.0'
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'product'
      MYSQL_USER: 'product'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

    volumes:
      - 'mysql:/var/lib/mysql'



    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p password" ]
      retries: 3
      timeout: 5s

volumes:
  mysql:
    driver: local
